language: python
python:
- '2.7'
- '3.5'
- '3.6'
dist: trusty
services:
- docker
before_install:
- pip install codecov
- pip install pytest-cov
- pip install codacy-coverage
install:
- pip install .
- pip install -r requirements.txt
script:
- py.test ./ --cov=./ 
- PYTHONPATH=./ py.test ./ --cov=./ 
after_success:
- coverage xml
- python-codacy-coverage -r coverage.xml
- codecov
